import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import HopDong from '@/models/HopDong';
import HoaDon from '@/models/HoaDon';
import KhachThue from '@/models/KhachThue';
import ThongBao from '@/models/ThongBao';
import ToaNha from '@/models/ToaNha';
import { sendDebtNotificationEmail, isValidEmail } from '@/lib/mail';

export const dynamic = 'force-dynamic';

/**
 * API Cron Job: Daily Payment Reminder
 * Triggered by Vercel Cron or manually
 * 
 * Logic:
 * 1. Check CRON_SECRET for security
 * 2. Find contracts where today is the payment day
 * 3. Find unpaid auto-generated invoices for those contracts
 * 4. Send email notifications to tenants
 */
export async function GET(request: NextRequest) {
  try {
    // 1. Security Check
    const authHeader = request.headers.get('authorization');
    const cronSecret = process.env.CRON_SECRET;
    
    // In production, we strictly check the secret. 
    // In development, we might skip if not set, but better to be safe.
    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await dbConnect();

    const today = new Date();
    const currentDay = today.getDate();
    const currentMonth = today.getMonth() + 1;
    const currentYear = today.getFullYear();

    console.log(`[Cron] Starting daily reminder for day ${currentDay}, ${currentMonth}/${currentYear}`);

    // 2. Find active contracts due today
    const dueContracts = await HopDong.find({
      trangThai: 'hoatDong',
      ngayThanhToan: currentDay
    }).select('_id maHopDong nguoiDaiDien');

    if (dueContracts.length === 0) {
      return NextResponse.json({ 
        message: 'No contracts due today',
        date: `${currentDay}/${currentMonth}/${currentYear}`
      });
    }

    const results = {
      processed: 0,
      sent: 0,
      errors: [] as string[]
    };

    // 3. Process each contract
    for (const contract of dueContracts) {
      results.processed++;

      // Find the corresponding unpaid auto-invoice for this month
      const invoice = await HoaDon.findOne({
        hopDong: contract._id,
        thang: currentMonth,
        nam: currentYear,
        isAutoGenerated: true,
        trangThai: 'chuaThanhToan'
      })
      .populate('khachThue')
      .populate({
        path: 'phong',
        populate: { path: 'toaNha' }
      });

      if (!invoice) {
        // No invoice found or already paid/manual
        continue;
      }

      const tenant = invoice.khachThue as any;
      
      if (tenant && tenant.email && isValidEmail(tenant.email)) {
        try {
          // Generate a simple QR URL if not present (optional)
          // For now, we rely on the helper to handle it
          const success = await sendDebtNotificationEmail({
            email: tenant.email,
            khachThueName: tenant.hoTen,
            hoaDonData: invoice,
            qrUrl: invoice.checkoutUrl || '' 
          });

            if (success) {
              results.sent++;
              // Update invoice to track notifications sent
              invoice.lanGuiEmailNhacNo = (invoice.lanGuiEmailNhacNo || 0) + 1;
              invoice.ngayGuiEmailNhacNoCuoi = new Date();
              await invoice.save();
            } else {
              results.errors.push(`Failed to send email to ${tenant.email} for invoice ${invoice.maHoaDon}`);
            }

            // Create In-App Notification (Independent of email success)
            try {
              const ownerId = (invoice.phong as any)?.toaNha?.chuSoHuu;
              const noiDungThongBao = `Nhắc nhở: Hóa đơn tháng ${invoice.thang}/${invoice.nam} của bạn đến hạn thanh toán vào hôm nay. Số tiền: ${new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(invoice.conLai)}.`;

              await new ThongBao({
                tieuDe: 'Nhắc nhở đóng tiền (Hôm nay)',
                noiDung: noiDungThongBao,
                loai: 'hoaDon',
                nguoiGui: ownerId || null,
                nguoiNhan: [invoice.khachThue],
                ngayGui: new Date()
              }).save();
            } catch (notifyErr) {
              console.error('Failed to create in-app notification:', notifyErr);
            }
          } catch (err: any) {
          results.errors.push(`Error processing ${tenant.email}: ${err.message}`);
        }
      } else {
        results.errors.push(`Tenant for invoice ${invoice.maHoaDon} has no valid email`);
      }
    }

    return NextResponse.json({
      message: 'Daily reminder cron completed',
      date: `${currentDay}/${currentMonth}/${currentYear}`,
      summary: results
    });

  } catch (error: any) {
    console.error('[Cron Error] Daily reminder failed:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
